spring:
  profiles:
    active: minikube
  application:
    name: restaurant-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 9091


